// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btqafofotwfisceytxbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cWFmb2ZvdHdmaXNjZXl0eGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjA2MzQsImV4cCI6MjA2OTAzNjYzNH0.6ok55N5DEEzaGpwkJH5iVFN71J5Ij9joyjCqWxSFMK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});